[[questions]]
id = "23c95879-aae2-4121-bf89-21278f7b6ec6"
type = "MultipleChoice"
prompt.prompt = """
以下哪项**不是**使用模块的好处？
"""
answer.answer = "模块能提升同一模块内相互依赖代码的运行时性能"
prompt.distractors = [
  "模块将相关代码分组，使程序员更容易处理大型代码库",
  "模块封装不应被外部客户端使用的实现细节",
  "模块提供作用域，避免代码库各部分之间的命名冲突"
]
context = """
模块对运行时没有影响，它们纯粹用于编译时的代码组织。
"""
