[[questions]]
id = "da6daf92-5b2c-4f8d-97de-6905dbc77936"
type = "MultipleChoice"
prompt.prompt = "以下哪个说法最能解释为什么 Rust 不允许字符串索引？"
answer.answer = "字符串索引存在歧义，因为字符串可以表示多种粒度的有序数据"
prompt.distractors = [
  "字符串索引不安全，因为它可能导致段错误或缓冲区溢出",
  "字符串索引效率低下，因为字符串以空字符结尾，无法高效计算其长度",
  "字符串索引会让 Rust 太容易使用，而 Rust 开发者需要保住饭碗"
]
context = """
UTF-8 字符串可以被解释为字节序列、字符序列或字素簇序列。这些方式中没有哪一种是解释字符串的"默认"方式，
因此默认的索引操作没有意义。
"""

[[questions]]
id = "9366278e-a3f5-4759-ac72-e3c7d248da44"
type = "MultipleChoice"
prompt.prompt = """
以下哪个说法最能描述字符串切片 `&str` 与字节切片 `&[u8]` 类型之间的区别？
"""
answer.answer = "`&str` 指向的字节始终可以被解释为 UTF-8，而 `&[u8]` 可以是任意字节序列"
prompt.distractors = [
  "`&str` 始终指向存储在程序二进制文件中的数据，而 `&[u8]` 可以存储在内存的任何位置",
  "`&str` 不能被进一步切片，而 `&[u8]` 可以再次切片",
  "`&str` 可以从 `String` 构造，而 `&[u8]` 只能来自 `Vec`"
]
context = """
`&str` 保证其指向的字节序列始终是有效的 UTF-8。因此，想要打印 `&str` 的程序员无需检查其是否有效，
也无需担心意外解释无效字符串。
"""
