[[questions]]
id = "e3a093e2-4809-4aa1-95b4-427833d8d23d"
type = "Tracing"
prompt.program = """
use std::rc::Rc;
fn main() {
    let r1 = Rc::new(0);
    let r4 = {
        let r2 = Rc::clone(&r1);
        Rc::downgrade(&r2)
    };
    let r5 = Rc::clone(&r1);
    let r6 = r4.upgrade();
    println!("{} {}", Rc::strong_count(&r1), Rc::weak_count(&r1));
}
"""
answer.doesCompile = true
answer.stdout = "3 1"
context = """
三个强引用分别是 `r1`、`r5` 和 `r6`。唯一的弱引用是 `r4`，它在 `main` 结束时被释放。`r2` 在其作用域结束时被释放。
"""
