[[questions]]
id = "53cb3740-2962-4379-a25f-a65e72812a95"
type = "Tracing"
prompt.program = """
use std::thread;
fn main() {
    let mut n = 1;
    let t = thread::spawn(move || {
        n = n + 1;
        thread::spawn(move || {
            n = n + 1;
        })
    });
    n = n + 1;
    t.join().unwrap().join().unwrap();
    println!("{n}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
`move` 关键字会将 `n` 复制到闭包中，因此 `thread::spawn` 内部的 `n = n + 1` 赋值对外部的 `n` 没有影响。
"""

[[questions]]
id = "c2a84e6d-8143-4944-bf20-b00e49144ac9"
type = "MultipleChoice"
prompt.prompt = """
考虑书中这个线程错误捕获 vector 的示例：

```
use std::thread;

fn main() {
    let v = vec![1, 2, 3];

    let handle = thread::spawn(|| {
        println!("Here's a vector: {:?}", v);
    });

    handle.join().unwrap();
}
```

Rust 编译器给出以下诊断信息：

```text
note: function requires argument type to outlive `'static`
 --> src/main.rs:6:18
  |
6 |       let handle = thread::spawn(|| {
  |  __________________^
7 | |         println!("Here's a vector: {:?}", v);
8 | |     });
  | |______^
```

回顾一下，`'static` 是在整个程序运行期间都有效的引用的生命周期。

以下哪项最准确地描述了"function requires argument type to outlive `'static`"这条说明？
"""
answer.answer = "Rust 不知道线程会运行多久，因此线程捕获的值必须永久有效"
prompt.distractors = [
    "传递给 `thread::spawn` 的闭包不允许接受任何参数",
    "vector `v` 包含的值的生命周期不超过 `'static`",
    "闭包只能捕获类型为 `&'static str` 的字符串常量"
]
context = """
如果闭包捕获了一个生命周期短于 `'static` 的值的引用，那么线程可能比该值存活更久，从而违反内存安全。注意，可以使用 [`thread::scope`](https://doc.rust-lang.org/std/thread/fn.scope.html) 来允许线程捕获非静态引用，方法是在静态上限制线程的生命周期。
"""
