# [[questions]]
# id = "b2dd44fc-2782-495e-bb54-65af8442c388"
# type = "MultipleChoice"
# prompt.prompt = """
# **Program 1:**

# ```ide
# /// Adds the string `s` to all elements of
# /// the input iterator
# fn concat_all(
#     iter: impl Iterator<Item = String>,
#     s: &str
# ) -> impl Iterator<Item = String> {
#     iter.map(move |s2| s2 + s)
# }
# ```

# If you tried to compile this program, which of the following best describes the compiler error you would get?
# """
# answer.answer = "the returned iterator captures a lifetime that isn't in the bounds of `impl Iterator<Item = String>`"
# prompt.distractors = [
#   "`s2 + s` is not valid because `s` and `s2` have different lifetimes",
#   "the closure `|s2| s2 + s` cannot move out of a shared reference",
#   "`iter.map(..)` does not implement the trait `Iterator<Item = String>`"
# ]
# context = """
# The string reference `s` has an implicit lifetime `'a`. The closure passed to `iter.map(..)` captures this string reference, but the type `impl Iterator<Item = String>` does not mention `'a`. Therefore the iterator captures a lifetime not in its bounds.
# """


# [[questions]]
# id = "816e9376-7161-4f41-bc04-9dba8413d7a7"
# type = "MultipleChoice"
# prompt.prompt = """
# **Program 1:**

# ```ide
# /// Adds the string `s` to all elements of
# /// the input iterator
# fn concat_all(
#     iter: impl Iterator<Item = String>,
#     s: &str
# ) -> impl Iterator<Item = String> {
#     iter.map(move |s2| s2 + s)
# }
# ```

# Normally if you try to compile this function, the compiler returns the following error:

# ```text
# error[E0700]: hidden type for `impl Iterator<Item = String>` captures lifetime that does not appear in bounds
#  --> test.rs:7:5
#   |
# 5 |     s: &str
#   |        ---- hidden type `Map<impl Iterator<Item = String>, [closure@test.rs:7:14: 7:23]>` captures the anonymous lifetime defined here
# 6 | ) -> impl Iterator<Item = String> {
# 7 |     iter.map(move |s2| s2 + s)
# ```

# Assume that the compiler did NOT reject this function. Which (if any) of the following programs would
# (1) pass the compiler, and (2) possibly cause undefined behavior if executed?
# Check each program that satisfies both criteria, OR check "None of these programs" if none are satisfying.
# """
# answer.answer = [
# """
# ```
# let v = vec![String::from("Rust")];
# let it = {
#     let s = String::from("Yes");
#     concat_all(v.into_iter(), &s)
# };
# it.collect::<Vec<_>>();
# ```
# """
# ]
# prompt.distractors = [
# """
# ```
# let v = vec![String::from("Rust")];
# concat_all(v.into_iter(), "Yes")
#     .collect::<Vec<_>>();
# ```
# """,
# """
# ```
# let v = vec![String::from("Rust")];
# let s = String::from("Yes");
# concat_all(v.into_iter(), &s);
# println!("{}", s);
# ```
# """,
# "None of these programs"
# ]
# context = """
# If the returned iterator isn't related to the lifetime of `s`, then memory safety is violated if:
# 1. `s` does not live forever (i.e. it's not `&'static str` like a string literal)
# 2. the return value of `concat_all` is used after `s` is dropped

# Then the expression `s2 + s` would dereference `s`, a read of deallocated memory.
# """

# [[questions]]
# id = "404b2cf7-7d29-45d7-86c4-7c806a071d7b"
# type = "MultipleChoice"
# prompt.prompt = """
# **Program 1:**

# ```ide
# /// Adds the string `s` to all elements of
# /// the input iterator
# fn concat_all(
#     iter: impl Iterator<Item = String>,
#     s: &str
# ) -> impl Iterator<Item = String> {
#     iter.map(move |s2| s2 + s)
# }
# ```

# Of the following fixes (highlighted in yellow), which fix best satisfies these three criteria:
# 1. The fixed function passes the Rust compiler,
# 2. The fixed function preserves the intention of the original code, and
# 3. The fixed function does not introduce unnecessary inefficiencies
# """
# answer.answer = """
# ```ide
# fn concat_all`[<'a>]`(
#     iter: impl Iterator<Item = String> `[+ 'a]`,
#     s: &`['a]` str
# ) -> impl Iterator<Item = String> `[+ 'a]` {
#     iter.map(move |s2| s2 + s)
# }
# ```
# """
# prompt.distractors = [
# """
# ```ide
# fn concat_all(
#     iter: impl Iterator<Item = String>,
#     s: &`['static]` str
# ) -> impl Iterator<Item = String> {
#     iter.map(move |s2| s2 + s)
# }
# ```
# """,
# """
# ```ide
# fn concat_all`[<'a, 'b>]`(
#     iter: impl Iterator<Item = String> `[+ 'a]`,
#     s: &`['b]` str
# ) -> impl Iterator<Item = String> `[+ 'a + 'b]` {
#     iter.map(move |s2| s2 + s)
# }
# ```
# """,
# """
# ```ide
# fn concat_all(
#     iter: impl Iterator<Item = String>,
#     s: `[String]`
# ) -> impl Iterator<Item = String> {
#     iter.map(move |s2| s2 + `[&s]`)
# }
# ```
# """,
# ]
# context = """
# To fix this issue, we need to express the relationship between the lifetimes of `iter`, `s`, and the return type. The best way to do this is a lifetime variable `<'a>` and require that `iter` and `s` both live for `'a`, and that the output type also lives for `'a`.
# """


[[questions]]
id = "2c6d6e2e-ad6e-4e98-bf88-8cada144ebee"
type = "MultipleChoice"
prompt.prompt = """
**程序 1：**

```ide
/// 将一个实现了 Display 的对象添加到
/// Display trait 对象的 vector 中
use std::fmt::Display;
fn add_displayable<T: Display>(
    v: &mut Vec<Box<dyn Display>>,
    t: T
) {
    v.push(Box::new(t));
}
```

如果你尝试编译此程序，以下哪项最准确地描述了编译器错误？
"""
answer.answer = "将类型 `T` 转换为 trait 对象时，其生命周期不够长"
prompt.distractors = [
  "类型 `T` 可能是动态大小类型，无法转换为 trait 对象",
  "如果类型 `T` 包含引用，则无法被装箱",
  "类型 `T` 的生命周期不超过引用 `&mut Vec<..>` 的生命周期"
]
context = """
将 `Box<T>` 转换为 `Box<dyn Display>`（在 `v.push(..)` 中隐式发生）时，Rust 要求 trait 对象 `dyn Display` 的生命周期必须超过 vector。然而，`T` 的生命周期未作指定，因此 `T` 的存活时间可能不够长。
"""


[[questions]]
id = "36da4652-baeb-47a6-9ee1-1448b02cbe8e"
type = "MultipleChoice"
prompt.prompt = """
**程序 1：**

```ide
/// 将一个实现了 Display 的对象添加到
/// Display trait 对象的 vector 中
use std::fmt::Display;
fn add_displayable<T: Display>(
    v: &mut Vec<Box<dyn Display>>,
    t: T
) {
    v.push(Box::new(t));
}
```

通常情况下，如果你尝试编译此函数，编译器会返回以下错误：

```text
error[E0310]: the parameter type `T` may not live long enough
 --> test.rs:6:12
  |
6 |     v.push(Box::new(t));
  |            ^^^^^^^^^^^
```

假设编译器*没有*拒绝此函数。以下哪些程序会（1）通过编译器，且（2）执行时可能引发未定义行为？勾选满足两个条件的程序，若都不满足则勾选"以上程序都不是"。"""
answer.answer = [
"""
```
let mut v: Vec<Box<dyn Display>> = Vec::new();
{
    let n = 0;
    add_displayable(&mut v, &n);
}
println!("{}", v[0]);
```
""",
]
prompt.distractors = [
  "以上程序都不是",
"""
```
let mut v: Vec<Box<dyn Display>> = Vec::new();
{
    let s = String::from("Hello world");
    add_displayable(&mut v, s);
}
println!("{}", v[0]);
```
""",
"""
```
let mut v: Vec<Box<dyn Display>> = Vec::new();
add_displayable(&mut v, 5);
```
"""
]
context = """
该程序存在内存不安全。要造成内存安全违规，程序必须创建一个包含引用的类型 `T`，且这些引用的生命周期短于 vector。例如，添加 `&n`，而 `n` 在 `v` 之前离开作用域，这意味着后续使用 `v[0]` 时会读取已释放的内存。
"""


[[questions]]
id = "2da21d0e-5722-4908-b528-dc87bbce1faf"
type = "MultipleChoice"
prompt.prompt = """
**程序 1：**

```ide
/// 将一个实现了 Display 的对象添加到
/// Display trait 对象的 vector 中
use std::fmt::Display;
fn add_displayable<T: Display>(
    v: &mut Vec<Box<dyn Display>>,
    t: T
) {
    v.push(Box::new(t));
}
```

在以下修复方案（黄色高亮显示）中，哪个方案最能同时满足以下三个标准：
1. 修复后的函数能通过 Rust 编译器，
2. 修复后的函数保留了原始代码的意图，且
3. 修复后的函数不引入不必要的低效
"""
answer.answer = """
```ide
fn add_displayable<`['a]`, T: Display `[+ 'a]`>(
    v: &mut Vec<Box<dyn Display `[+ 'a]`>>,
    t: T
) {
    v.push(Box::new(t));
}
```
"""
prompt.distractors = [
"""
```ide
fn add_displayable<T: Display `[+ 'static]`>(
    v: &mut Vec<Box<dyn Display>>,
    t: T
) {
    v.push(Box::new(t));
}
```
""",
"""
```ide
fn add_displayable<T: Display `[+ Clone]`>(
    v: &mut Vec<Box<dyn Display>>,
    t: T
) {
    v.push(Box::new(`[t.clone()]`));
}
```
""",
"""
```ide
fn add_displayable<`['a]`, T: Display `[+ 'a]`>(
    v: &`['a]` mut Vec<Box<dyn Display>>,
    t: T
) {
    v.push(Box::new(t));
}
```
""",
]
context = """
最惯用的修复方式是指定 `T` 的生命周期与 trait 对象 `dyn Display` 的生命周期之间的关系。这里的做法是：添加生命周期参数 `'a`，要求 `T` 的生命周期超过 `'a`，且 trait 对象的生命周期也至少为 `'a`。

使用 `'static` 约束虽然效果相同，但更差：它的表达能力更弱，使得 vector 中的 trait 对象永远不能持有引用。将生命周期 `'a` 放在 `&'a mut Vec<..>` 引用上是不正确的，也无法修复编译器错误。
"""
