[multipart]
q = """
**背景：** 你正在设计一个简单的事件系统，它会在响应事件时调用回调函数。

**功能：** `Events` 结构体提供注册回调的函数。
回调分为两种：可并行执行的（可在多个线程上运行）和顺序执行的（只能在主线程上运行）。

**设计方案：** 以下是几种实现该功能的设计方案。

```
pub struct Events {
	// ...
}

// Option 1: parallel and sequential are two separate methods
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
	pub fn register_sequential<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
}

// Option 2: parallel and sequential are two members of an enum
pub enum Callback<F> {
	Parallel(F),
	Sequential(F)
}
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: Callback<F>) { /* .. */ }
}

// Option 3: parallel and sequential are markers in a trait method
pub trait Register<Marker, F, E> {
	fn register(&mut self, f: F);
}
pub struct Parallel;
pub struct Sequential;
impl<F, E> Register<Parallel, F, E> for Events
where F: Fn(E) {
	fn register(&mut self, f: F) { /* .. */ }
}
impl<F, E> Register<Sequential, F, E> for Events
where F: Fn(Sequential, E) {
	fn register(&mut self, f: F) { /* .. */ }
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
选出满足以下需求的每个设计方案：

**需求：** 回调默认应被视为可并行执行，且 API 应体现该默认行为。
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1", "3"]
context = """
首先，让我们想象在每种设计下注册回调是什么样的：

```rust
// Option 1
events.register(|e: OnClick| { /* .. */ });
events.register_sequential(|e: OnClick| { /* .. */ })

// Option 2
events.register(Callback::Parallel(|e: OnClick| { /* .. */ }));
events.register(Callback::Sequential(|e: OnClick| { /* .. */ }));

// Option 3
events.register(|e: OnClick| { /* .. */ });
events.register(|_: Sequential, e: OnClick| { /* .. */ });
```

在这些方案中，方案 1 和方案 3 体现了并行是默认模式，因为它对应最简单的用法。
顺序执行需要使用更长的方法名（`_sequential`）或标记类型（`_: Sequential`）。

方案 2 没有明确标示并行应为默认值，因为 `Parallel` 和 `Sequential` 都必须传入
`register`。
"""
id = "4a32bad8-fee7-45b5-80ef-775d059aab48"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
选出满足以下需求的每个设计方案：

**需求：** API 应尽可能少地导出方法。
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2", "3"]
context = """
方案 2 和方案 3 只导出一个 `register` 方法。方案 1 需要导出两个名称不同的注册方法。
"""
id = "eaeafdad-ac3a-4d92-85eb-995991a81c2d"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
选出满足以下需求的每个设计方案：

**需求：** API 应尽可能少地依赖编译器的类型推断系统。
"""
prompt.distractors = ["3"]
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
方案 1 和方案 2 除了推断函数 `F` 的类型外，不需要太多类型推断。

方案 3 通过创建一个以"标记"类型为参数的 `Register` trait 来实现重载技巧。
回顾它的两次注册调用：
```
events.register(|e: OnClick| { /* .. */ })
events.register(|_: Sequential, e: OnClick| { /* .. */ })
```

这两次调用看起来使用的是同一个实现，但实际上引用的是同一方法的不同实现。
这个实现依赖编译器在解析每次 `.register(..)` 调用对应哪个 `Register` 实现时推断 `Marker` 的类型。
因此，如果我们的目标是*不*依赖类型推断，那么方案 3 是不合适的。
"""
id = "e0c4f766-b82a-496a-b669-ea9e0a367af7"
