[[questions]]
id = "35e59c95-3d83-4277-8d88-a1986f4086d7"
type = "MultipleChoice"
prompt.prompt = """
考虑对某类型 `T` 的表达式进行模式匹配。
以下哪项最准确地描述了可反驳模式与不可反驳模式之间的区别？
"""
answer.answer = "可反驳模式不匹配类型 `T` 的某些值，而不可反驳模式匹配类型 `T` 的所有值"
prompt.distractors = [
    "可反驳模式匹配另一类型 `S` 的某些值，而不可反驳模式只匹配类型 `T` 的值",
    "可反驳模式不匹配类型 `T` 的任何值，而不可反驳模式匹配类型 `T` 的某些值",
    "可反驳模式是指 `T` 为枚举类型时的模式，而不可反驳模式是指 `T` 不为枚举类型时的模式"
]
context = """
如果存在某个预期类型的值不被该模式匹配，则该模式是可反驳的。
"""

[[questions]]
id = "3c29eb2d-cbe9-4a2c-99b8-aa5c6467c8b4"
type = "MultipleChoice"
prompt.prompt = """
考虑以下程序：

```
let x: &[(i32, i32)] = &[(0, 1)];
```

以下哪些是 `x` 的**可反驳**模式？
"""
answer.answer = [
    "`&[(x, y)]`",
    "`&[(x, y), ..]`",
]
prompt.distractors = [
    "`&[..]`",
    "`_`"
]
context = """
切片没有固定长度，因此任何断言 `x` 必须至少有一个元素的模式都是可反驳的。
"""
